<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - Password Confrimation</name>
   <tag></tag>
   <elementGuidId>8ccd6236-ab50-4daa-a08a-bd68b8bdd649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PASSWD_CRFM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWD_CRFM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffb555fe-952f-47e0-bc8c-c3a4e28c0d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>72c5f6f1-a7a3-4dd6-aa92-7337b6189e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PASSWD_CRFM</value>
      <webElementGuid>9fd63943-666a-462d-accb-03cb84e299b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWD_CRFM</value>
      <webElementGuid>c683c9c5-5bef-4388-9dc7-d32f7d73ed99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-input-md k-rounded-md k-input-solid</value>
      <webElementGuid>403ab17c-294d-4b00-8f16-91e9b0004414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWD_CRFM&quot;)</value>
      <webElementGuid>25941e45-f97c-425f-80a1-94ab25a17d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWD_CRFM']</value>
      <webElementGuid>3a769926-4bf5-4bd3-8fc5-afaa335da405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-contentc1b57f43-4f7d-47ad-9d97-ffd5aa4a1df7']/div/div/div[2]/form/fieldset/div[3]/div/div/div[2]/input</value>
      <webElementGuid>509c1a04-434c-4bcd-86d0-f40222690895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>b646615b-30bb-4978-950b-f5eb13db4933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'PASSWD_CRFM' and @id = 'PASSWD_CRFM']</value>
      <webElementGuid>7b611746-928a-4fc4-949c-9ffa009b84a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
