<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - Password</name>
   <tag></tag>
   <elementGuidId>cba6f111-8070-4e25-81fe-906d94b74c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PASSWD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7f9c4ff-380a-4f1b-b6c0-7b3782865c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a8ebdddb-d150-49c3-8a52-f99b141323d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PASSWD</value>
      <webElementGuid>6ad6e712-f08e-4e88-9236-69c7d1a6b420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWD</value>
      <webElementGuid>6c22af02-9674-460c-9ca6-22ebbf4bddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-input-md k-rounded-md k-input-solid</value>
      <webElementGuid>0b9681e2-6495-4779-9132-d40de8c3aad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>fd034764-a257-43ee-bde3-0f631c8ce62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWD&quot;)</value>
      <webElementGuid>319485ec-94ca-4e10-b245-81193bb18908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWD']</value>
      <webElementGuid>b1d5bd59-8127-4195-880d-3b5d9a795503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-contentc1b57f43-4f7d-47ad-9d97-ffd5aa4a1df7']/div/div/div[2]/form/fieldset/div[2]/div/div/div[2]/input</value>
      <webElementGuid>f935889d-baf5-4380-8f48-764f732fc6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div/div[2]/input</value>
      <webElementGuid>ab0afb11-21b3-4ea0-bf1f-639f830b74e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'PASSWD' and @id = 'PASSWD']</value>
      <webElementGuid>30645b77-d82b-4b4a-ba5b-6f3601d34b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
