<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - User ID</name>
   <tag></tag>
   <elementGuidId>0a755b1c-3a1d-4b12-90db-50eec8ef2e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USR_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USR_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fbb1060-79e1-4973-8ef8-e0aaa8ffdd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4f472969-e046-4a8d-8d41-f1e345f81751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USR_ID</value>
      <webElementGuid>d53963b2-0061-4f01-89c3-b9476febb153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USR_ID</value>
      <webElementGuid>f5786b1b-09b8-4b57-8298-24d43927cb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-input-md k-rounded-md k-input-solid</value>
      <webElementGuid>8d698448-887b-4144-a459-b277d3670046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USR_ID&quot;)</value>
      <webElementGuid>0a7b50a2-d741-40e7-a623-17bf5973d564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USR_ID']</value>
      <webElementGuid>6dcacf89-a78b-4ee0-a443-5778d7f8160b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-contentc1b57f43-4f7d-47ad-9d97-ffd5aa4a1df7']/div/div/div[2]/form/fieldset/div/div/div/div[2]/input</value>
      <webElementGuid>54e29883-40f6-4c72-8de8-abee93c6332e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div[2]/input</value>
      <webElementGuid>ed9f7557-5d88-443b-bd4d-a6a64ba65d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'USR_ID' and @id = 'USR_ID']</value>
      <webElementGuid>2f9494fb-5ad7-40db-b06d-74cd2b4abdcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
