<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - Last Name</name>
   <tag></tag>
   <elementGuidId>2c49f686-0b18-437f-9b33-3cb53ee9dfd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LAST_NM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LAST_NM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>427f4773-5989-4cfe-86f4-0f14e69bbb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a1eb4aa3-e233-4e62-ae83-0b6ff6c51755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LAST_NM</value>
      <webElementGuid>ad279adf-58cc-44b4-a163-6b0ed134ea0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LAST_NM</value>
      <webElementGuid>5c79ec2d-ea00-4c36-b795-9011f6fed795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-input-md k-rounded-md k-input-solid</value>
      <webElementGuid>8b713eba-3207-4902-99d1-93f4990d6969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LAST_NM&quot;)</value>
      <webElementGuid>6eaf3c33-e717-47ca-8144-abf72836a70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LAST_NM']</value>
      <webElementGuid>03f9ed05-afb9-43d3-8eed-4526a8e398c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-contentc1b57f43-4f7d-47ad-9d97-ffd5aa4a1df7']/div/div/div[2]/form/fieldset/div[5]/div/div/div[2]/input</value>
      <webElementGuid>4be6c43a-475f-4391-b75b-82013377a3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/input</value>
      <webElementGuid>cb7cabbc-dce0-4d79-85f2-ce632e2cf5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'LAST_NM' and @id = 'LAST_NM']</value>
      <webElementGuid>19bf81ef-8558-4df8-a561-12ea0ccb1da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
