<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - Position</name>
   <tag></tag>
   <elementGuidId>198fba5b-1b8d-4e1f-88e0-43ad679e052a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#POSITION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='POSITION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed8fa3fd-f0bf-4071-b753-f3d43b1d0749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4295d85a-7e94-4e9d-8717-0ea2ca4bf77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>POSITION</value>
      <webElementGuid>487109e8-fcf9-43fc-b52b-24e2338e9985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>POSITION</value>
      <webElementGuid>73b81136-6e70-4ee2-bbf5-e7b51ce5e34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-input-md k-rounded-md k-input-solid</value>
      <webElementGuid>ff9073bd-6f9b-4605-a92c-7c1099560da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;POSITION&quot;)</value>
      <webElementGuid>6e2b0f10-aba2-463e-98cf-c2fd248a4802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='POSITION']</value>
      <webElementGuid>bfa6ead9-5b9b-4240-8081-c302a9510642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-contentc1b57f43-4f7d-47ad-9d97-ffd5aa4a1df7']/div/div/div[2]/form/fieldset/div[7]/div/div/div[2]/input</value>
      <webElementGuid>807b36f2-831f-44bc-bd8e-c5c3b078f9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/input</value>
      <webElementGuid>a782e666-0247-43ec-980f-0a132bc31faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'POSITION' and @id = 'POSITION']</value>
      <webElementGuid>9087bdb6-8662-4f31-bc96-49134a6aebb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
