<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field - Employee ID</name>
   <tag></tag>
   <elementGuidId>cb6ba596-965c-4f15-876a-2f1da7322706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EMPLOYEE_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EMPLOYEE_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0331b06-cf67-48a9-9637-bb1e12d62c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d76dd204-277f-484e-ba3f-c8980badf7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EMPLOYEE_ID</value>
      <webElementGuid>3c74d924-26f7-4674-b12a-448571c2f142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EMPLOYEE_ID</value>
      <webElementGuid>41e0e259-f8b7-4477-88ec-4e4d10b21a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input k-input-md k-rounded-md k-input-solid</value>
      <webElementGuid>7da3d00a-0cf8-43fd-86b7-8dfbd0cac8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EMPLOYEE_ID&quot;)</value>
      <webElementGuid>be9144c1-7829-46cc-a8b7-d782348d1436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EMPLOYEE_ID']</value>
      <webElementGuid>587cd8ba-6f26-4eb6-9660-7429c8a529b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-contentc1b57f43-4f7d-47ad-9d97-ffd5aa4a1df7']/div/div/div[2]/form/fieldset/div[6]/div/div/div[2]/input</value>
      <webElementGuid>ec7b09f1-df82-40de-886b-8c28e0b16a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/input</value>
      <webElementGuid>dbbfc623-338f-41d6-bbb4-a16387bdb2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EMPLOYEE_ID' and @id = 'EMPLOYEE_ID']</value>
      <webElementGuid>021c6c1f-73c8-4c8f-88e3-4f69169585aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
