<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert - Save Data Successfully</name>
   <tag></tag>
   <elementGuidId>24db9c24-51df-4a35-a445-67398304b233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toast.toast-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Save DataData Successfully Saved, and Pending for Approval' or . = 'Save DataData Successfully Saved, and Pending for Approval')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6bddd97-f3c2-4f75-86ca-a16e207e6862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast toast-success</value>
      <webElementGuid>c986be45-24d1-4b63-aaed-72a7420dd240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>f55c7ee4-e5b3-4284-8548-ccb0231805ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save DataData Successfully Saved, and Pending for Approval</value>
      <webElementGuid>383a28f9-9833-4b0a-b572-607117188dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;toast toast-success&quot;]</value>
      <webElementGuid>0e528cfd-6ff6-497b-815b-c0c7411be143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>69a6126c-23f8-4b2a-b70e-e2be58c19b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amartha Regulatory Reporting &amp; Analytics (ARRA)'])[1]/following::div[2]</value>
      <webElementGuid>d6d71196-7b40-40c7-8a63-e204c6d80bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>e6cfa976-e33f-4307-8f2d-4a2526cb693c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Save DataData Successfully Saved, and Pending for Approval' or . = 'Save DataData Successfully Saved, and Pending for Approval')]</value>
      <webElementGuid>1b3cfad2-da05-4b24-982f-937c9e7ab883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
