<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - Add</name>
   <tag></tag>
   <elementGuidId>b9c2d861-b093-464b-8060-b19d749322b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ADD&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='ADD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>392878b0-2a60-4db0-a948-b5c38b7724c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-md k-rounded-md k-button-flat k-button-flat-base</value>
      <webElementGuid>379fc847-e5a0-426d-8ad0-66b9d940a08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ADD</value>
      <webElementGuid>901dc195-12ce-49a6-9523-3ca3f705102a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD</value>
      <webElementGuid>d6867609-6970-4acc-b1b2-1cfae5372cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0600b94f-929f-4ea6-8dbe-3a960af07e18&quot;)/div[@class=&quot;k-appbar-section&quot;]/button[@class=&quot;k-button k-button-md k-rounded-md k-button-flat k-button-flat-base&quot;]</value>
      <webElementGuid>261db0d9-e783-4bb8-9008-99ecd16aded2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='ADD']</value>
      <webElementGuid>cec9d43c-3151-458a-a09a-5a33ac0c734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0600b94f-929f-4ea6-8dbe-3a960af07e18']/div/button</value>
      <webElementGuid>33658f9c-3fea-4e3a-9d20-f12e5a2a1fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User User Configuration'])[1]/following::button[6]</value>
      <webElementGuid>c0b5bad0-9083-4aaa-8c32-45867680be07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Security Configuration'])[1]/following::button[6]</value>
      <webElementGuid>918d2071-7c7b-4aa3-9c20-361319c27986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/preceding::button[1]</value>
      <webElementGuid>cc9c7c3a-b794-4dc6-8ea8-e135de9ebed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFRESH'])[1]/preceding::button[1]</value>
      <webElementGuid>cca69d00-8616-42e7-b1c2-8a35a6c0e051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD']/parent::*</value>
      <webElementGuid>037f48a7-4394-4d06-9c27-71d8a2f7d531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>c64c98db-dd3b-4fc6-a151-b64dd55457c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'ADD' and (text() = 'ADD' or . = 'ADD')]</value>
      <webElementGuid>84adae83-571d-4996-bcbc-2a21f9dbc869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
