<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4aafa689-286c-4207-ab77-5eea18413c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='getting-started']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Swagger logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3bdf1ddd-05ce-4a97-a543-874e21527d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/swagger-logo-horizontal.jpeg</value>
      <webElementGuid>c60611ee-013e-4db3-9fa9-964b2a336792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Swagger logo</value>
      <webElementGuid>d8cb7b43-f754-424d-89fc-6fcde1c1b4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getting-started&quot;)/div[@class=&quot;swagger-link&quot;]/a[1]/img[1]</value>
      <webElementGuid>e6f33598-67ea-4e86-b959-3d090888b47c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='getting-started']/div/a/img</value>
      <webElementGuid>89cfcb26-b3a5-4ddd-b867-c5282bde722f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Swagger logo']</value>
      <webElementGuid>627aab15-4d1c-4eed-b8bf-b1ec0c6c387e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/a/img</value>
      <webElementGuid>7c9c930c-b17c-47e9-96bf-1a10b68645f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/swagger-logo-horizontal.jpeg' and @alt = 'Swagger logo']</value>
      <webElementGuid>cfe58b16-2359-475e-8b1f-393c7e6d5133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
