<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo-Dashboard Amartek</name>
   <tag></tag>
   <elementGuidId>c1ed7c54-2caa-4fba-a206-81b0c6bef425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/aside/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a18933ac-0505-4179-ba12-66d1c233bdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>4e7bde6a-d04c-41da-a402-7356fdc2d3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/aside[@class=&quot;ant-layout-sider ant-layout-sider-dark arra-scrollable-container&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/a[1]/div[@class=&quot;logo&quot;]</value>
      <webElementGuid>0467d635-c2b7-4b2e-b4bb-de14202b1253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/aside/div/a/div</value>
      <webElementGuid>a30742f9-7bc1-44a4-9b01-b2fd8088120c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>597d46f1-362f-4d4c-96ff-984d614d36c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
